services:
  mask-rcnn-cpu:
    container_name: mask-rcnn-cpu
    build:
      context: ./
      dockerfile: docker/dev/mask-rcnn/Dockerfile-cpu
    command: python -u test.py # Testing flask app
    environment:
      - USE_CPU=true # Custom environment variable to indicate CPU use
    networks:
      - backend
    ports:
      - "5002:5002" # Map container port 5002 to host port 50002
    # Uncomment and modify if volumes needed:
    # volumes:
    #   - ./path/to/volume:/path/inside/container

networks:
  backend:
    name: backend
    driver: bridge
