name: ClassXTool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.7.*
  - matplotlib==3.4.3
  - astropy==5.1
  - flask==3.0.*
  - flask-sqlalchemy
  - sqlalchemy==1.4.*
  - python-dotenv
  - pymysql
  - PyJWT
  - pandas
  - ca-certificates
  - certifi
  - cython
  - pip
  - pip:
      - h5py==3.10.*
      - flask-session==0.7.*
      - scikit-image==0.23.*
      - scikit-learn==1.5.*
      - opencv-python==4.8.*
      - sunpy[all] 
      - aiapy
      - xgboost
      - imutils
      - gunicorn
      - authlib
      - pylint
      - cachelib
      - celery
      - redis
      - pycocotools
